# https://sasstools.github.io/make-sass-lint-config/

# Make sure tabs are not used in this file

rules:
  indentation: 0
  quotes: 0
  class-name-format: 0
  empty-line-between-blocks: 0
  nesting-depth: 
    - 1
    - max-depth: 6
  property-sort-order: 0
  final-newline: 0
  mixins-before-declarations: 0
  no-transition-all: 0
  no-qualifying-elements: 0
  zero-unit: 0
  no-important: 0
  border-zero: 0
  space-around-operator: 0
  leading-zero: 0
  no-trailing-whitespace: 0
  no-vendor-prefixes: 0
  no-css-comments: 0
  space-before-brace: 0
  space-after-colon: 0