<?php
/**
 * Generate ACF Fields
 *
 * @package fp-slider
 */

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5d1f53b6f3d01',
			'title'                 => 'Slider',
			'fields'                => array(
				array(
					'key'               => 'field_5fa5edd8bf0db',
					'label'             => 'Custom CSS Class',
					'name'              => 'custom_css_class',
					'type'              => 'text',
					'instructions'      => 'Add a custom class for each slide for custom styling',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5d1f5499dca8e',
					'label'             => 'Content',
					'name'              => 'content',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5cc40c2afee22',
							'label'             => 'Display Options',
							'name'              => 'display_options',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'image'      => 'Image',
								'text_image' => 'Text+Image',
								'video'      => 'Video',
								'text_video' => 'Text+Video',
							),
							'default_value'     => 'text_image',
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_615f0d8ecfe86',
							'label'             => 'Use as accordion slide?',
							'name'              => 'accordion_slide',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 1,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						array(
							'key'               => 'field_615f0f1fcfe87',
							'label'             => 'Accordion Slide Header',
							'name'              => 'accordion_slide_header',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_615f0d8ecfe86',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Expand Slide',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f91e1e7e17e4',
							'label'             => 'Text Box Image',
							'name'              => 'content_image',
							'type'              => 'image',
							'instructions'      => 'Optional: Upload an image for placement above the header text on a slide. Max height: 84px',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '84px',
							'max_size'          => '',
							'mime_types'        => '.jpg,.png,.svg,.jpeg',
						),
						array(
							'key'               => 'field_5cc40c43fee23',
							'label'             => 'Heading',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5cc40c5cfee24',
							'label'             => 'Description',
							'name'              => 'description',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5cc40c6ffee25',
							'label'             => 'Button Text',
							'name'              => 'button_text',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f073248b52e7',
							'label'             => 'Video URL',
							'name'              => 'video_url',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'video',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'https://youtu.be/h6fcK_fRYaI',
						),
						array(
							'key'               => 'field_5cc40c82fee26',
							'label'             => 'Url',
							'name'              => 'url',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5cc40c91fee27',
							'label'             => 'Link Target',
							'name'              => 'link_target',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'_self'  => 'Same Window',
								'_blank' => 'New Window',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_5d1f5560ebe62',
							'label'             => 'Mobile Banner Image',
							'name'              => 'mobile_banner_image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_5dc3e92c99b2d',
							'label'             => 'Mobile App Image',
							'name'              => 'mobile_app_image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
				array(
					'key'               => 'field_5d1f54bcdca8f',
					'label'             => 'Styling',
					'name'              => 'styling',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5cc40c2afee22',
								'operator' => '==contains',
								'value'    => 'text',
							),
						),
						array(
							array(
								'field'    => 'field_615f0d8ecfe86',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5cc40caafee28',
							'label'             => 'Text Box Alignment',
							'name'              => 'text_box_alignment',
							'type'              => 'radio',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'left'   => 'Left',
								'center' => 'Center',
								'right'  => 'Right',
							),
							'allow_null'        => 0,
							'other_choice'      => 0,
							'default_value'     => '',
							'layout'            => 'vertical',
							'return_format'     => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key'               => 'field_5cc40d3ffee29',
							'label'             => 'Transparent Text Box',
							'name'              => 'transparent_text_box',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						array(
							'key'               => 'field_5cd1a7f141cb8',
							'label'             => 'Text Box Background Color',
							'name'              => 'text_box_background_color',
							'type'              => 'color_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40d3ffee29',
										'operator' => '!=',
										'value'    => '1',
									),
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
						),
						array(
							'key'               => 'field_5cd1a80f41cb9',
							'label'             => 'Heading Color',
							'name'              => 'heading_color',
							'type'              => 'color_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
						),
						array(
							'key'               => 'field_5cd1a82a41cba',
							'label'             => 'Description Color',
							'name'              => 'description_color',
							'type'              => 'color_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
						),
						array(
							'key'               => 'field_5cd1a83941cbb',
							'label'             => 'Button Background Color',
							'name'              => 'button_background_color',
							'type'              => 'color_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
						),
						array(
							'key'               => 'field_5cd1a85641cbc',
							'label'             => 'Button Text Color',
							'name'              => 'button_text_color',
							'type'              => 'color_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5cc40c2afee22',
										'operator' => '==contains',
										'value'    => 'text',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
						),
						array(
							'key'               => 'field_615e47a66e3f8',
							'label'             => 'Accordion Slide Color',
							'name'              => 'slide_color',
							'type'              => 'color_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_615f0d8ecfe86',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '#C4D82E',
						),
						array(
							'key'               => 'field_615e48f3ccb07',
							'label'             => 'Accordion Active Icon Color',
							'name'              => 'active_icon_color',
							'type'              => 'color_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_615f0d8ecfe86',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
						),
					),
				),
				array(
					'key'               => 'field_5dbb259da9917',
					'label'             => 'Regionalization',
					'name'              => 'regionalization',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5dbb26a16210e',
							'label'             => 'Include',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'open'              => 1,
							'multi_expand'      => 1,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_5dbb25cda9918',
							'label'             => 'Regionalization Include Region',
							'name'              => 'regionalization_include_region',
							'type'              => 'taxonomy',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'taxonomy'          => 'region',
							'field_type'        => 'checkbox',
							'add_term'          => 0,
							'save_terms'        => 0,
							'load_terms'        => 0,
							'return_format'     => 'object',
							'multiple'          => 0,
							'allow_null'        => 0,
						),
						array(
							'key'               => 'field_5dbb250bf53ba',
							'label'             => 'Regionalization Include Store',
							'name'              => 'regionalization_include_store',
							'type'              => 'post_object',
							'instructions'      => 'Regionalize this slide to specific store(s).',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'store',
							),
							'taxonomy'          => '',
							'allow_null'        => 0,
							'multiple'          => 1,
							'return_format'     => 'id',
							'ui'                => 1,
						),
						array(
							'key'               => 'field_5dbb26bd6210f',
							'label'             => 'Exclude',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'open'              => 0,
							'multi_expand'      => 0,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_5dbb270162111',
							'label'             => 'Regionalization Exclude Region',
							'name'              => 'regionalization_exclude_region',
							'type'              => 'taxonomy',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'taxonomy'          => 'region',
							'field_type'        => 'checkbox',
							'add_term'          => 0,
							'save_terms'        => 0,
							'load_terms'        => 0,
							'return_format'     => 'object',
							'multiple'          => 0,
							'allow_null'        => 0,
						),
						array(
							'key'               => 'field_5dbb270062110',
							'label'             => 'Regionalization Exclude Store',
							'name'              => 'regionalization_exclude_store',
							'type'              => 'post_object',
							'instructions'      => 'Regionalize this slide to specific store(s).',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'store',
							),
							'taxonomy'          => '',
							'allow_null'        => 0,
							'multiple'          => 1,
							'return_format'     => 'id',
							'ui'                => 1,
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'slide',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	endif;
